/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CatalogsColorsRouteImport } from './routes/catalogs/colors'
import { Route as CatalogsMaterialsRouteImport } from './routes/catalogs/materials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsColorsRoute = CatalogsColorsRouteImport.update({
  id: '/catalogs/colors',
  path: '/catalogs/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsMaterialsRoute = CatalogsMaterialsRouteImport.update({
  id: '/catalogs/materials',
  path: '/catalogs/materials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalogs/colors': typeof CatalogsColorsRoute
  '/catalogs/materials': typeof CatalogsMaterialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalogs/colors': typeof CatalogsColorsRoute
  '/catalogs/materials': typeof CatalogsMaterialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalogs/colors': typeof CatalogsColorsRoute
  '/catalogs/materials': typeof CatalogsMaterialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/catalogs/colors' | '/catalogs/materials'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/catalogs/colors' | '/catalogs/materials'
  id: '__root__' | '/' | '/about' | '/catalogs/colors' | '/catalogs/materials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogsColorsRoute: typeof CatalogsColorsRoute
  CatalogsMaterialsRoute: typeof CatalogsMaterialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/colors': {
      id: '/catalogs/colors'
      path: '/catalogs/colors'
      fullPath: '/catalogs/colors'
      preLoaderRoute: typeof CatalogsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/materials': {
      id: '/catalogs/materials'
      path: '/catalogs/materials'
      fullPath: '/catalogs/materials'
      preLoaderRoute: typeof CatalogsMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogsColorsRoute: CatalogsColorsRoute,
  CatalogsMaterialsRoute: CatalogsMaterialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
