/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatCatIdRouteImport } from './routes/cat.$catId'
import { Route as CatalogsBreedsRouteImport } from './routes/catalogs/breeds'
import { Route as CatalogsCoatsRouteImport } from './routes/catalogs/coats'
import { Route as CatalogsColorsRouteImport } from './routes/catalogs/colors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatCatIdRoute = CatCatIdRouteImport.update({
  id: '/cat/$catId',
  path: '/cat/$catId',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsBreedsRoute = CatalogsBreedsRouteImport.update({
  id: '/catalogs/breeds',
  path: '/catalogs/breeds',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsCoatsRoute = CatalogsCoatsRouteImport.update({
  id: '/catalogs/coats',
  path: '/catalogs/coats',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsColorsRoute = CatalogsColorsRouteImport.update({
  id: '/catalogs/colors',
  path: '/catalogs/colors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cat/$catId': typeof CatCatIdRoute
  '/catalogs/breeds': typeof CatalogsBreedsRoute
  '/catalogs/coats': typeof CatalogsCoatsRoute
  '/catalogs/colors': typeof CatalogsColorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cat/$catId': typeof CatCatIdRoute
  '/catalogs/breeds': typeof CatalogsBreedsRoute
  '/catalogs/coats': typeof CatalogsCoatsRoute
  '/catalogs/colors': typeof CatalogsColorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cat/$catId': typeof CatCatIdRoute
  '/catalogs/breeds': typeof CatalogsBreedsRoute
  '/catalogs/coats': typeof CatalogsCoatsRoute
  '/catalogs/colors': typeof CatalogsColorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cat/$catId'
    | '/catalogs/breeds'
    | '/catalogs/coats'
    | '/catalogs/colors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cat/$catId'
    | '/catalogs/breeds'
    | '/catalogs/coats'
    | '/catalogs/colors'
  id:
    | '__root__'
    | '/'
    | '/cat/$catId'
    | '/catalogs/breeds'
    | '/catalogs/coats'
    | '/catalogs/colors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatCatIdRoute: typeof CatCatIdRoute
  CatalogsBreedsRoute: typeof CatalogsBreedsRoute
  CatalogsCoatsRoute: typeof CatalogsCoatsRoute
  CatalogsColorsRoute: typeof CatalogsColorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cat/$catId': {
      id: '/cat/$catId'
      path: '/cat/$catId'
      fullPath: '/cat/$catId'
      preLoaderRoute: typeof CatCatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/breeds': {
      id: '/catalogs/breeds'
      path: '/catalogs/breeds'
      fullPath: '/catalogs/breeds'
      preLoaderRoute: typeof CatalogsBreedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/coats': {
      id: '/catalogs/coats'
      path: '/catalogs/coats'
      fullPath: '/catalogs/coats'
      preLoaderRoute: typeof CatalogsCoatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/colors': {
      id: '/catalogs/colors'
      path: '/catalogs/colors'
      fullPath: '/catalogs/colors'
      preLoaderRoute: typeof CatalogsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatCatIdRoute: CatCatIdRoute,
  CatalogsBreedsRoute: CatalogsBreedsRoute,
  CatalogsCoatsRoute: CatalogsCoatsRoute,
  CatalogsColorsRoute: CatalogsColorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
