/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CableProductCableProductIdRouteImport } from './routes/cableProduct.$cableProductId'
import { Route as CatalogsColorsRouteImport } from './routes/catalogs/colors'
import { Route as CatalogsMaterialsRouteImport } from './routes/catalogs/materials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CableProductCableProductIdRoute =
  CableProductCableProductIdRouteImport.update({
    id: '/cableProduct/$cableProductId',
    path: '/cableProduct/$cableProductId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalogsColorsRoute = CatalogsColorsRouteImport.update({
  id: '/catalogs/colors',
  path: '/catalogs/colors',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsMaterialsRoute = CatalogsMaterialsRouteImport.update({
  id: '/catalogs/materials',
  path: '/catalogs/materials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cableProduct/$cableProductId': typeof CableProductCableProductIdRoute
  '/catalogs/colors': typeof CatalogsColorsRoute
  '/catalogs/materials': typeof CatalogsMaterialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cableProduct/$cableProductId': typeof CableProductCableProductIdRoute
  '/catalogs/colors': typeof CatalogsColorsRoute
  '/catalogs/materials': typeof CatalogsMaterialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cableProduct/$cableProductId': typeof CableProductCableProductIdRoute
  '/catalogs/colors': typeof CatalogsColorsRoute
  '/catalogs/materials': typeof CatalogsMaterialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cableProduct/$cableProductId'
    | '/catalogs/colors'
    | '/catalogs/materials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cableProduct/$cableProductId'
    | '/catalogs/colors'
    | '/catalogs/materials'
  id:
    | '__root__'
    | '/'
    | '/cableProduct/$cableProductId'
    | '/catalogs/colors'
    | '/catalogs/materials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CableProductCableProductIdRoute: typeof CableProductCableProductIdRoute
  CatalogsColorsRoute: typeof CatalogsColorsRoute
  CatalogsMaterialsRoute: typeof CatalogsMaterialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cableProduct/$cableProductId': {
      id: '/cableProduct/$cableProductId'
      path: '/cableProduct/$cableProductId'
      fullPath: '/cableProduct/$cableProductId'
      preLoaderRoute: typeof CableProductCableProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/colors': {
      id: '/catalogs/colors'
      path: '/catalogs/colors'
      fullPath: '/catalogs/colors'
      preLoaderRoute: typeof CatalogsColorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs/materials': {
      id: '/catalogs/materials'
      path: '/catalogs/materials'
      fullPath: '/catalogs/materials'
      preLoaderRoute: typeof CatalogsMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CableProductCableProductIdRoute: CableProductCableProductIdRoute,
  CatalogsColorsRoute: CatalogsColorsRoute,
  CatalogsMaterialsRoute: CatalogsMaterialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
